### ISSUE TITLE
channel order issue with H5reader()

### ISSUE THREAD

**Issue by cwfink** [spice-herald/pytesdaq#17]
When using ```H5Reader.read_many_events()``` using the ```detector_chans``` argument, the channels are not returned in the order specified by the list provided to ```detector_chans```. 

Either the function should be changed such that the channels are returned in the order specified. Or it should be made clear in the documentation that the channels can only be returned in a specific order. This could lead to lots of confusion down the road.

**Comment by slwatkins** [comment]
@serfass It looks like the issue comes down to these lines in the hdf5.py file:

https://github.com/berkeleytes/pytesdaq/blob/29af7d4b752cf3a8ba7dc5cb8684cb7d995bd229/pytesdaq/io/hdf5.py#L551-L588

L564 in particular doesn't respect the order of `detector_chans`, but instead uses the order in the connection dictionary. Do you have any ideas on the best way to fix this?

**Comment by serfass** [comment]
Yes, it is a bit annoying. I was trying to preserve the original  ADC channel order (and array).  
Let me see what can be done.
